lab/Components/CartViewComponent.cs
using lab.Models;
using Microsoft.AspNetCore.Mvc;

namespace lab.Components
{
    public class CartViewComponent : ViewComponent
    {
        private Cart _cart;
        public CartViewComponent(Cart cart)
        {
            _cart = cart;
        }

        public IViewComponentResult Invoke()
        {
            return View(_cart);
        }
    }
}

lab/Components/MenuViewComponent.cs
using lab.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace lab.Components
{
    public class MenuViewComponent : ViewComponent
    {
        //Инициализация списка элементов меню
        private List<MenuItem> _menuItems = new List<MenuItem>
        {
            new MenuItem{ Controller="Home", Action="Index", Text="Lab 2" }, 
            new MenuItem{ Controller="Product", Action="Index", Text="Products" },
            new MenuItem{ IsPage=true, Area="Admin", Page="/Index", Text="Admin" },
            new MenuItem{ IsPage=true, Area="ApiDemo", Page="/Index", Text="API-demo" }
         };

        public IViewComponentResult Invoke()
        {
            //Получение значений сегментов маршрута
            var routeValues = ViewContext.RouteData.Values;
            var controller = routeValues["controller"];
            var page = routeValues["page"];
            var area = routeValues["area"];

            foreach (var item in _menuItems)
            {
                //Название контроллера совпадает?
                var _matchController = controller?.Equals(item.Controller) ?? false;

                //Название зоны совпадает?

                var _matchArea = area?.Equals(item.Area) ?? false;
                //Если есть совпадение, то сделать элемент меню активным
                //(применить соответствующий класс CSS)
                if (_matchController || _matchArea)
                {
                    item.Active = "active";
                }
            }
            return View(_menuItems);
        }
    }
}

lab/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="container">
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <a class="navbar-brand" href="/">Shupranova</a>
                @await Component.InvokeAsync("Menu")
                <partial name="_UserPartial" />
            </nav>
        </div>
    </header>

    <main class="container cust-main cust-has-padding-t-b">
        @RenderBody()
    </main>

    <footer>
        <div class="container">
            <div class="navbar navbar-dark navbar-expand-md bg-dark">
                <div class="navbar-nav ml-auto">
                    <a class="nav-item nav-link" href="http://www.facebook.com">
                        <i class="fab fa-facebook-f fa-2x"></i>
                    </a><a class="nav-item nav-link" href="http://www.vk.com">
                        <i class="fab fa-vk fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.twitter.com">
                        <i class="fab fa-twitter fa-2x"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

lab/Views/Shared/_UserPartial.cshtml
@using Microsoft.AspNetCore.Identity;
@using lab.DAL.Entities;
@inject SignInManager<ApplicationUser> signInManager

@if (signInManager.IsSignedIn(User))
{
    @await Component.InvokeAsync("Cart")
    <div class="dropdown ml-4 nav-color">
        <div class="dropdown-toggle" id="dropdownMenuButton"
             data-toggle="dropdown" aria-haspopup="true"
             aria-expanded="false">
            <img img-action="GetAvatar" img-controller="Image" width="30" alt="User" class="rounded" />
        </div>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
            <div class="dropdown-item-text">
                <img img-action="GetAvatar" img-controller="Image" width="50" alt="User" class="rounded" />
                @User.Identity.Name
            </div>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" asp-controller="Cart" aspaction="Index">My Products</a>
            <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnurl="@ViewContext.HttpContext.Request.Path">
                Logout
            </a>
        </div>
    </div>
}
else
{
    <ul class="nav navbar-nav ml-auto">
        <li>
            <a class="nav-item nav-link" asp-area="Identity" asp-page="/Account/Login">
                Log In
            </a>
        </li>
        <li>
            <a class="nav-item nav-link" asp-area="Identity" asp-page="/Account/Register">
                Sign Up
            </a>
        </li>
    </ul>
}